server:
  port: 3355
spring:
  profiles:
    active: dev

---
spring:
  application:
    name:  micro-service-cloud-config-dev
  profiles: dev
server:
  port: 3355

---
spring:
  profiles: test
  application:
    name: micro-service-cloud-config-test
server:
  port: 4455

---
spring:
  application:
    name: micro-service-cloud-config-prod
  profiles: prod
server:
  port: 5566
