server:
  port: 3344

---
spring:
  application:
    name:  micro-service-cloud-config-dev
  profiles: dev

---
spring:
  profiles: test
  application:
    name: micro-service-cloud-config-test

---
spring:
  application:
    name: micro-service-cloud-config-prod
  profiles: prod